### PR TITLE
less verbose

### PR DESCRIPTION
**Pull request by rurban**
log truncated

### CODE REVIEW

**Comment by rurban** [comment]
..

**Comment by ribasushi** [comment]
@rurban - is this repo needed anymore? It *seems* to me you nailed the core issue. Is this correct?

**Comment by rurban** [comment]
Yes, the readonly stash issue https://github.com/perl11/cperl/issues/171 is fixed in cperl.
Not in perl5 though, you need to change the testcase then.

**Comment by ribasushi** [comment]
I've given up on directly reporting bugs to p5p, just like you :/
I'll make a note of this elsewhere

**Pull request closed without merging**
